# Generated by Django 4.1.4 on 2023-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinebot', '0002_rename_name_movie_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Year_of_release',
            new_name='Year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='Rating',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
