# Generated by Django 4.1.4 on 2023-01-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinebot', '0003_rename_year_of_release_movie_year_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='test'),
        ),
    ]
